global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'webapp'
    static_configs:
      - targets: ['webapp-service:80']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-service:5432']
